from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Protocol


class CorpusAdapter(Protocol):
    def corpus_id(self) -> str: ...

    def section_types(self) -> tuple[str, ...]: ...

    def version(self) -> str: ...

    def default_language(self) -> str: ...

    def node_type(self, node: int) -> str: ...

    def node_from_section(self, values: Sequence[str], lang: str) -> int | None: ...

    def section_from_node(self, node: int, lang: str) -> tuple[str, ...]: ...

    def slots(self, node: int) -> tuple[int, ...]: ...

    def units_of_type(self, otype: str) -> Iterable[int]: ...
